# Use a recent Node runtime 
FROM node:22-alpine

# Set the working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json (if available)
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the client code
COPY . .

# Expose Vite's default port
EXPOSE 5173

# Run Vite and expose the host network
CMD ["npm", "run", "dev", "--", "--host"]